version: '3'
services:
    node:
        depends_on:
            - mongo
        build:
            context: ./node
        volumes:
            - './node:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - COMPOSE_HTTP_TIMEOUT=200
        command: sh -c " sleep 5000000000; yarn start"

    mongo:
        image: mongo
        ports:
            - "27016:27017"
        volumes:
            - './node/data:/data/db'

    react:
        depends_on:
            - node
        build:
          context: ./react
        volumes:
          - './react:/usr/src/app'
          - '/usr/src/app/node_modules'
        ports:
          - '3000:3000'
        command: sh -c "yarn; yarn start"

volumes:
  data-volume:
